##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/joqe9849/back-rently.mathieudacheux.fr/
    - /bin/cp -R package.json $DEPLOYPATH
    - /bin/cp -R package-lock.json $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp -R dist $DEPLOYPATH
