#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if npm run prettier; then
  echo "Prettier passed ✅"
else
  echo "Tests failed ❌"
  exit 1
fi

if npm run test; then
  echo "Tests passed ✅"
  exit 0
else
  echo "Tests failed ❌"
  exit 1
fi